from typing import Any

__version__: str

class QuantusClient:
    def __init__(self, config: str) -> None: ...
    def reconcile(self) -> dict[str, Any]: ...
    def discover(self) -> dict[str, Any]: ...
    def data_stream_setup(self) -> dict[str, Any]: ...
    def open_stream(self) -> StreamReader: ...
    def write_settings(self, item_id: int, values: dict[str, str | float]) -> bool: ...
    def auto_zero(self, item_id: int | None = None) -> None: ...
    def bridge_balance(self, item_id: int | None = None) -> None: ...
    def bridge_balance_reset(self, item_id: int | None = None) -> None: ...
    def put_can_message_list(self, item_id: int, messages: Any) -> None: ...
    def can_transmit(self, item_id: int) -> None: ...
    def suspend_stream(self) -> None: ...
    def resume_stream(self) -> None: ...

class StreamReader:
    def next_event(self, timeout_ms: int = 1000) -> dict[str, Any] | None: ...
    def health(self) -> dict[str, Any]: ...
    def close(self) -> None: ...
