class Circuit:
    def __init__(self) -> None: ...
    def add_psu(self, id: str, r_series: float = 0.0) -> None: ...
    def attach_synthetic_load(self, psu_id: str, kind: str, **params: float) -> None: ...
    def set_psu_mode(self, id: str, mode: str) -> None: ...
    def set_psu_voltage_setpoint(self, id: str, volts: float) -> None: ...
    def set_psu_current_limit(self, id: str, amps: float) -> None: ...
    def set_psu_voltage_max(self, id: str, volts: float = ...) -> None: ...
    def set_psu_r_series(self, id: str, ohms: float) -> None: ...
    def set_psu_output_enabled(self, id: str, enabled: bool) -> None: ...
    def set_psu_remote_sense(self, id: str, enabled: bool) -> None: ...
    def step(self, dt_seconds: float) -> None: ...
    def psu_voltage(self, id: str) -> float: ...
    def psu_current(self, id: str) -> float: ...
    def psu_mode(self, id: str) -> str: ...
