site_name: "instro SDK"
repo_url: "https://github.com/nominal-io/instro"
repo_name: "nominal-io/instro"
site_dir: site
watch: [mkdocs.yml, ../../README.md, ../../CHANGELOG.md, ../../instro, ../../packages]
copyright: Copyright &copy; Nominal, Inc.
edit_uri: edit/main/docs/reference/
docs_dir: src

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

extra_css:
  - css/mkdocstrings.css

nav:
  - Overview:
      - index.md
  - Library:
      - Instrument: reference/instrument.md
      - Types: reference/types.md
      - Exceptions: reference/exceptions.md
      - Publishers: reference/publishers.md

  - Instruments:
      - instruments/index.md
      - DAQ: instruments/daq.md
      - DMM: instruments/dmm.md
      - PSU: instruments/psu.md
      - Electronic Load: instruments/eload.md
      - I2C: instruments/i2c.md
  - Protocols:
      - protocols/index.md
      - Modbus: protocols/modbus.md
  - Examples:
      - examples/index.md
      - DAQ:
          - examples/daq/daq_read_analog_sw_timed.md
          - examples/daq/daq_read_analog_hw_timed.md
          - examples/daq/daq_read_analog_hw_timed_no_background.md
          - examples/daq/daq_write_analog_sw_timed.md
          - examples/daq/daq_read_digital_line.md
          - examples/daq/daq_write_digital_line.md
          - examples/daq/daq_read_digital_port.md
          - examples/daq/daq_write_digital_port.md
          - examples/daq/daq_relays.md
          - examples/daq/daq_analog_loopback.md
      - DMM:
          - examples/dmm/dmm_basic.md
      - PSU:
          - examples/psu/psu.md
          - examples/psu/psu_background_daemon.md
      - Electronic Load:
          - examples/eload/eload.md
      - I2C:
          - examples/i2c/i2c_basic.md
          - examples/i2c/i2c_command.md
      - Publishers:
          - examples/publishers/publish_buffered.md
          - examples/publishers/publish_custom.md
          - examples/publishers/publish_file.md
          - examples/publishers/publish_queued.md
      - Modbus:
          - examples/modbus/minimal_example.md
          - examples/modbus/modbus_example.md
          - examples/modbus/programmatic_config_example.md
          - examples/modbus/labjack_t4_loopback_test.md
      - EtherNet/IP:
          - examples/ethernetip/minimal_example.md
          - examples/ethernetip/ethernetip_example.md
          - examples/ethernetip/programmatic_config_example.md
      - Test Rack:
          - examples/test_rack_example/test_rack.md
      - Custom:
          - examples/custom/simple_temp_controller.md
  - Changelog:
      - changelog.md

theme:
  name: material
  logo: logo.svg
  favicon: favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.magiclink
  - pymdownx.snippets:
      base_path:
        - !relative $config_dir
        - !relative $config_dir/../..
        - !relative $config_dir/../../examples
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      toc_depth: 4
      permalink: "¤"
  - attr_list

plugins:
  - search
  - gen-files:
      scripts:
        - generate_examples.py
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            heading_level: 3
            inherited_members: true
            show_if_no_docstring: true
            merge_init_into_class: true
            members_order: source
            parameter_headings: true
            separate_signature: true
            line_length: 72
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            show_source: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nominal-io
